language: rust

os: linux

# Doesn't seem to do much. 
# Always rebuilds everything.
# cache: cargo

before_install:
  - sudo apt-get install libudev-dev

rust:
  - nightly
  - stable

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose
  - RUST_BACKTRACE=1 cargo test --verbose
