language: rust

os: linux

before_install:
  - sudo apt-get install libudev-dev
  #- sudo apt-get install libssl-dev
  #- sudo apt-get install pkg-config

rust:
  - nightly
  - stable

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose
  - RUST_BACKTRACE=1 cargo test --verbose
