[package]
name = "websocket_serial_server"
version = "0.1.0"
authors = ["Daniel Joyce <daniel.a.joyce@gmail.com>"]

[dependencies]
argparse = "0.2.1"
base64 = "0.5.1"
daemonize = "0.2.3"
env_logger = "0.4.2"
error-chain = "0.10.0"
hyper = "0.10.9"
log = "0.3.7"
rand = "0.3.15"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.2"
##serialport = "1.0.1"
##serialport = { path = "../serialport-rs" }
serialport = {git = "https://daniel.a.joyce@gitlab.com/daniel.a.joyce/serialport-rs.git", branch = "fix-fd-leaks"}
thread-control = "0.1.2"
websocket = "0.19.1"

[[bin]]
name = "wsssd"
path = "src/main.rs"
