[package]
name = "websocket_serial_server"
version = "0.1.0"
authors = ["Daniel Joyce <daniel.a.joyce@gmail.com>"]

[dependencies]
hyper = "0.10.9"
websocket = "0.19.1"
serialport = "1.0.1"
serde = "1.0.2"
argparse = "0.2.1"
serde_json = "1.0.1"
serde_derive = "1.0.2"

[[bin]]
name = "wsss"
path = "src/main.rs"
