[package]
name = "websocket_serial_server"
version = "0.1.0"
authors = ["Daniel Joyce <daniel.a.joyce@gmail.com>"]
description = "A websocket server providing access to local serial ports"
readme = "README.md"
license-file = "LICENSE"

[dependencies]
argparse = "0.2.1"
base64 = "0.5.1"
daemonize = "0.2.3"
env_logger = "0.4.2"
error-chain = "0.10.0"
hyper = "0.10.9"
log = "0.3.7"
rand = "0.3.15"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.2"
##serialport = "1.0.1"
##serialport = { path = "../serialport-rs" }
serialport = {git = "https://daniel.a.joyce@gitlab.com/daniel.a.joyce/serialport-rs.git", branch = "fix-fd-leaks-3"}
thread-control = "0.1.2"
toml = "0.4.1"
websocket = "0.19.1"

[dev-dependencies]
tempfile = "2.1.5"

[lib]
name="serial_support"
path="src/serial_support/mod.rs"

[[bin]]
name = "wsss"
path = "src/main.rs"
