[package]
name = "websocket_serial_server"
version = "0.1.0"
authors = ["Daniel Joyce <daniel.a.joyce@gmail.com>"]

[dependencies]
argparse = "0.2.1"
base64 = "0.5.1"
daemonize = "0.2.3"
env_logger = "0.4.2"
hyper = "0.10.9"
log = "0.3.7"
serialport = "1.0.1"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.1"
thread-control = "0.1.2"
websocket = "0.19.1"

[[bin]]
name = "wsssd"
path = "src/main.rs"
