[package]
edition = "2018"
name = "websocket_serial_server"
version = "0.2.0"
authors = ["Daniel Joyce <daniel.a.joyce@gmail.com>"]
description = "A websocket server providing access to local serial ports"
readme = "README.md"
license-file = "LICENSE"

[dependencies]
actix = "0.8.3"
actix-web = "1.0.8"
argparse = "0.2.2"
base64 = "0.10.1"
daemonize = "0.4.1"
debug_stub_derive = "0.3.0"
env_logger = "0.7.1"
error-chain = "0.12.1"
failure = "0.1.6"
log = "0.4.8"
rand = "0.7.2"
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.41"
serialport = "3.3.0"
toml = "0.5.3"
actix-web-actors = "1.0.2"
actix-codec = "0.1.2"

[dev-dependencies]
tempfile = "3.1.0"

[lib]
name="lib"
path="src/lib/mod.rs"

[[bin]]
name = "wsss"
path = "src/bin/main.rs"
